import { date, numeric, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

import { categories } from "./categories";
import { householdMembers } from "./householdMembers";
import { households } from "./households";
import { recurringExpenses } from "./recurringExpenses";

export const expenses = pgTable("expenses", {
  id: uuid("id").defaultRandom().primaryKey(),
  householdId: uuid("household_id")
    .notNull()
    .references(() => households.id, { onDelete: "cascade" }),
  amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
  categoryId: uuid("category_id")
    .notNull()
    .references(() => categories.id, { onDelete: "cascade" }),
  // null = shared
  ownerMemberId: uuid("owner_member_id").references(() => householdMembers.id, {
    onDelete: "cascade",
  }),
  paidByMemberId: uuid("paid_by_member_id")
    .notNull()
    .references(() => householdMembers.id, { onDelete: "cascade" }),
  date: date("date").notNull(),
  note: text("note"),
  // Set when this expense was generated by marking a recurring item paid.
  // Nullable + set-null-on-delete so deleting a recurring template never
  // touches the historical expenses it already generated.
  recurringExpenseId: uuid("recurring_expense_id").references(() => recurringExpenses.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
